version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dallal_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/dallal.db:/app/dallal.db # Persist database
    restart: unless-stopped
    networks:
      - dallal-net

  frontend:
    build: ./frontend
    container_name: dallal_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dallal-net

networks:
  dallal-net:
    driver: bridge
